### PR TITLE
Improve optics

### PR DESCRIPTION
**Pull request by fernandohds564**
Create function to calculate Touschek energy acceptance.

For a detailed description of the algorithm, please, check [this link](https://accelconf.web.cern.ch/ipac2017/papers/wepik052.pdf#search=%20domain%3Daccelconf%2Eweb%2Ecern%2Ech%20%20%2Bauthor%3A%22Dester%22%20%20FileExtension%3Dpdf%20%2Durl%3Aabstract%20%2Durl%3Aaccelconf%2Fjacow)

Executing the following code:
```
import time

import numpy as np
import matplotlib.pyplot as mplt
import matplotlib.gridspec as mgs
from matplotlib import rcParams

from pymodels import si
import pyaccel as pyacc

rcParams.update({
    'axes.grid': True, 'grid.alpha': 0.5, 'grid.linestyle': '--',
    'font.size': 12})

mod = si.create_accelerator()
mod.vchamber_on = True
mod.cavity_on = True
mod.radiation_on = True

spos = pyacc.lattice.find_spos(mod, indices='closed')
t0_ = time.time()
accn0, accp0 = pyacc.optics.calc_tousheck_energy_acceptance(
    mod, track=False, check_tune=False,
    energy_offsets=np.linspace(0.02, 0.05, 40))
t1_ = time.time()
print(f'Basic took {(t1_-t0_):.3f}s')
accn1, accp1 = pyacc.optics.calc_tousheck_energy_acceptance(
    mod, track=False, check_tune=True,
    energy_offsets=np.linspace(0.02, 0.05, 40))
t2_ = time.time()
print(f'Tune took {(t2_-t1_):.3f}s')
accn2, accp2 = pyacc.optics.calc_tousheck_energy_acceptance(
    mod, track=True, check_tune=True,
    energy_offsets=np.linspace(0.02, 0.05, 40))
t3_ = time.time()
print(f'Tune Track took {(t3_-t2_):.3f}s')

fig = mplt.figure(figsize=(8, 5))
gs = mgs.GridSpec(1, 1)
ax = fig.add_subplot(gs[0, 0])
ax.plot(spos, accp0*100, color='tab:blue', label='Basic')
ax.plot(spos, accp1*100, color='tab:red', label='Tune')
ax.plot(spos, accp2*100, color='tab:green', label='Tune & Track')
ax.plot(spos, accn0*100, color='tab:blue')
ax.plot(spos, accn1*100, color='tab:red')
ax.plot(spos, accn2*100, color='tab:green')
pyacc.graphics.draw_lattice(mod, height=1, offset=0, gca=True)
ax.set_xlabel('Position [m]')
ax.set_ylabel('Enegy Acceptance [%]')
ax.legend(
    loc='lower center', bbox_to_anchor=(0.5, 1.0), fontsize='x-small',
    ncol=3)
ax.set_xlim([0, 518.4/5])
fig.tight_layout()
mplt.show()
```

Will result in:
```
Basic took 13.157s
Tune took 12.912s
Tune Track took 46.128s
```
image

### CODE REVIEW

**Review by anacso17 — APPROVED** [review]

**Comment by fernandohds564** [comment]
> @fernandohds564 , as it is, `calc_touschek _energy_acceptance` function is returning vectors whose sizes are incompatible with `Lifetime.accepen` that returns vectors of sizes defined by `EquilibriumParametersIntegrals`methods that use `indices='closed'`. It is very useful to have all these funcions returning vectors of the same size, otherwise awkward additions or deletions are necessary.
> 
> I created a temporary branch (https://github.com/lnls-fac/pyaccel/tree/improve-optics-indices-closed) with proposed modifications for your consideration. if you agree, you can merge it in this PR.

You are right @xresende . I noticed this yesterday when I used it in my studies. I is really very annoying having to add an extra point to the data. I will take a look at your branch, thks!

As a side note, I don't like this function the way it is today. I intend to transform it in a class in the future, because it does a lot of meaningful calculations to get to the final result which are thrown away. I also needs a lot more optional arguments to improve speed that are impractical to pass as functions arguments. Besides, even though the algorithm is very simple, it is also lengthy, which justifies breaking it in several parts, as methods of a class. 

We could also start thinking about changing the optics modulo into a subpackage, because the file is too big.

**Comment by fernandohds564** [comment]
@xresende I have accepted your suggestions. I also have added a few things to the function. That's why I asked you guys to revise this PR again.

**Comment by xresende** [comment]
> > @fernandohds564 , as it is, `calc_touschek _energy_acceptance` function is returning vectors whose sizes are incompatible with `Lifetime.accepen` that returns vectors of sizes defined by `EquilibriumParametersIntegrals`methods that use `indices='closed'`. It is very useful to have all these funcions returning vectors of the same size, otherwise awkward additions or deletions are necessary.
> > I created a temporary branch (https://github.com/lnls-fac/pyaccel/tree/improve-optics-indices-closed) with proposed modifications for your consideration. if you agree, you can merge it in this PR.
> 
> You are right @xresende . I noticed this yesterday when I used it in my studies. I is really very annoying having to add an extra point to the data. I will take a look at your branch, thks!
> 
> As a side note, I don't like this function the way it is today. I intend to transform it in a class in the future, because it does a lot of meaningful calculations to get to the final result which are thrown away. I also needs a lot more optional arguments to improve speed that are impractical to pass as functions arguments. Besides, even though the algorithm is very simple, it is also lengthy, which justifies breaking it in several parts, as methods of a class.
> 
> We could also start thinking about changing the optics modulo into a subpackage, because the file is too big.

yes, I also though that maybe it would be useful to make intermediate calculation results available. using a class seems the correct way to do it. i am not sure if it is possible but speeding the calculation would be nice. as it is noew, VACA, for example, cannot use it for touschek beam lifetime since it is too slow. VACA is currently using the optimistic energy acceptance defined by RF.

**Review by xresende — APPROVED** [review]

**Comment by xresende** [comment]
@fernandohds564 , there are conflicting files with the master branch

**Comment by fernandohds564** [comment]
> yes, I also thought that maybe it would be useful to make intermediate calculation results available. using a class seems the correct way to do it. i am not sure if it is possible but speeding the calculation would be nice. as it is noew, VACA, for example, cannot use it for touschek beam lifetime since it is too slow. VACA is currently using the optimistic energy acceptance defined by RF.

@xresende , I think this function is already as fast as it can be, considering our current version of trackcpp. The overall execution time is dominated by the calculation of the twiss parameters for off-energy particles (6.4s) and taking the `Twiss` parameters out of the `TwissList` object, and not on the algorithm per se. 
I have observed that this kind of operation is very slow:
```
betax = twi.betax
```
For the current sirius lattice it takes approximately 10ms! This is due to the fact that a lot of conversion has to be done in python to get these parameters. Maybe we could think about having C++ functions in `trackcpp` to this for us. 
Take a look at my last commit, for example. With only those changes I was able to reduce the execution time from ~12s to ~10s!

Regarding the algorithm itself, I have implemented a flag in the function to not consider the dependency of the optics functions with energy (`betax, alphax, etax`), but the resulting energy acceptance in this case was far off (the minimum was larger than 6%!), so I removed this flag before committing the change. So I don't see how we could simplify there...
Maybe the user could use a coarser mesh for the energies... This would decrease the energy resolution, but it seems there's room for a trade off..
We could also parallelize the twiss calculations in order to improve speed.

**Comment by fernandohds564** [comment]
> @fernandohds564 , there are conflicting files with the master branch

@xresende I have solved them. It must be fine with the current tip of the branch.

**Review by anacso17 — APPROVED** [review]

**Review by xresende — APPROVED** [review]

**Review by murilobalves — APPROVED** [review]

**Pull request merged**
